package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Juan Pablo Palomares Avila y Alvaro Bulnes Ramos
 */
public class VistaAñadirPersona extends javax.swing.JFrame {

    /**
     * Creates new form VistaAñadirPersona
     */
    public VistaAñadirPersona() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelIconos = new javax.swing.JPanel();
        jLabelIconoCredencial = new javax.swing.JLabel();
        jLabelIconoMail = new javax.swing.JLabel();
        jLabelIconoTelefono = new javax.swing.JLabel();
        jLabelIconoMapa = new javax.swing.JLabel();
        jLabelIconoCalendario = new javax.swing.JLabel();
        jLabelIconoEtiqueta = new javax.swing.JLabel();
        jPanelCampos = new javax.swing.JPanel();
        jPanelNombreApellido = new javax.swing.JPanel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldMail = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonAñadir = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanelIconos.setLayout(new java.awt.GridLayout(6, 1));

        jLabelIconoCredencial.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jLabelIconoCredencial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconoCredencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/user-id-icon.png"))); // NOI18N
        jLabelIconoCredencial.setIconTextGap(15);
        jPanelIconos.add(jLabelIconoCredencial);

        jLabelIconoMail.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jLabelIconoMail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconoMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/mail-icon.png"))); // NOI18N
        jLabelIconoMail.setIconTextGap(15);
        jPanelIconos.add(jLabelIconoMail);

        jLabelIconoTelefono.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jLabelIconoTelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconoTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/phone-icon.png"))); // NOI18N
        jLabelIconoTelefono.setIconTextGap(15);
        jPanelIconos.add(jLabelIconoTelefono);

        jLabelIconoMapa.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jLabelIconoMapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconoMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/map-icon.png"))); // NOI18N
        jLabelIconoMapa.setIconTextGap(15);
        jPanelIconos.add(jLabelIconoMapa);

        jLabelIconoCalendario.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabelIconoCalendario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconoCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/calendar-icon.png"))); // NOI18N
        jLabelIconoCalendario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelIconoCalendario.setIconTextGap(5);
        jPanelIconos.add(jLabelIconoCalendario);

        jLabelIconoEtiqueta.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jLabelIconoEtiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconoEtiqueta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/tag-icon.png"))); // NOI18N
        jLabelIconoEtiqueta.setIconTextGap(15);
        jPanelIconos.add(jLabelIconoEtiqueta);

        jPanelCampos.setLayout(new java.awt.GridLayout(6, 1));

        jPanelNombreApellido.setLayout(new java.awt.GridLayout(1, 2));

        jTextFieldNombre.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(24, 19, 9));
        jTextFieldNombre.setToolTipText("Nombre");
        jTextFieldNombre.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextFieldNombre.setSelectionColor(new java.awt.Color(255, 206, 91));
        jPanelNombreApellido.add(jTextFieldNombre);

        jTextFieldApellido.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jTextFieldApellido.setForeground(new java.awt.Color(24, 19, 9));
        jTextFieldApellido.setToolTipText("Apellido");
        jTextFieldApellido.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextFieldApellido.setSelectionColor(new java.awt.Color(255, 206, 91));
        jPanelNombreApellido.add(jTextFieldApellido);

        jPanelCampos.add(jPanelNombreApellido);

        jTextFieldMail.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jTextFieldMail.setForeground(new java.awt.Color(24, 19, 9));
        jTextFieldMail.setToolTipText("example@example.com");
        jTextFieldMail.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextFieldMail.setSelectionColor(new java.awt.Color(255, 206, 91));
        jPanelCampos.add(jTextFieldMail);

        jTextFieldTelefono.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jTextFieldTelefono.setForeground(new java.awt.Color(24, 19, 9));
        jTextFieldTelefono.setToolTipText("123456789");
        jTextFieldTelefono.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextFieldTelefono.setSelectionColor(new java.awt.Color(255, 206, 91));
        jPanelCampos.add(jTextFieldTelefono);

        jTextFieldDireccion.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jTextFieldDireccion.setForeground(new java.awt.Color(24, 19, 9));
        jTextFieldDireccion.setToolTipText("C/Ejemplo n3");
        jTextFieldDireccion.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextFieldDireccion.setSelectionColor(new java.awt.Color(255, 206, 91));
        jPanelCampos.add(jTextFieldDireccion);

        jDateChooser1.setToolTipText("");
        jPanelCampos.add(jDateChooser1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AMIGOS", "OTROS", "FAMILARES", "COMPAÑEROS DE TRABAJO", "COMPAÑEROS DE FACULTAD" }));
        jPanelCampos.add(jComboBox1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/silueta-icon.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jButtonAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/add-user-icon.png"))); // NOI18N
        jButtonAñadir.setText("Añadir");
        jButtonAñadir.setActionCommand("VistaAnyadir");

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/close-icon.png"))); // NOI18N
        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.setActionCommand("VistaAnyadir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jButtonAñadir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addComponent(jPanelIconos, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(jButtonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelIconos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public JTextField getjTextFieldApellido() {
        return jTextFieldApellido;
    }

    public JTextField getjTextFieldDireccion() {
        return jTextFieldDireccion;
    }

    public JTextField getjTextFieldMail() {
        return jTextFieldMail;
    }

    public JTextField getjTextFieldNombre() {
        return jTextFieldNombre;
    }

    public JTextField getjTextFieldTelefono() {
        return jTextFieldTelefono;
    }

    /**
     * @param args the command line arguments
     */
   

    public JButton getjButtonAñadir() {
        return jButtonAñadir;
    }


    public JButton getjButtonCerrar() {
        return jButtonCerrar;
    }

    public JDateChooser getjDateChooser1() {
        return jDateChooser1;
    }

 
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIconoCalendario;
    private javax.swing.JLabel jLabelIconoCredencial;
    private javax.swing.JLabel jLabelIconoEtiqueta;
    private javax.swing.JLabel jLabelIconoMail;
    private javax.swing.JLabel jLabelIconoMapa;
    private javax.swing.JLabel jLabelIconoTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCampos;
    private javax.swing.JPanel jPanelIconos;
    private javax.swing.JPanel jPanelNombreApellido;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
