/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;

import java.awt.Dimension;
import java.util.LinkedList;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Pablo Palomares Avila y Alvaro Bulnes Ramos
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
        limpiarTabla();
        jLabeldobleclick.setVisible(false);
        setTitle("AGENDA TELEFONICA");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCabecera = new javax.swing.JPanel();
        jPanelFiltro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabeldobleclick = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jPanelBotonera = new javax.swing.JPanel();
        jButtonConectar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContactos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCabecera.setPreferredSize(new java.awt.Dimension(850, 80));
        jPanelCabecera.setLayout(new java.awt.BorderLayout());

        jPanelFiltro.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/tag-icon.png"))); // NOI18N

        jLabelCategoria.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelCategoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCategoria.setText("Categoría:");
        jLabelCategoria.setIconTextGap(10);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "AMIGOS", "OTROS", "FAMILARES", "COMPAÑEROS DE TRABAJO", "COMPAÑEROS DE FACULTAD" }));
        jComboBox1.setActionCommand("VistaPrincipal");

        jLabeldobleclick.setText("DOBLE CLICK en un contacto para más datos");

        javax.swing.GroupLayout jPanelFiltroLayout = new javax.swing.GroupLayout(jPanelFiltro);
        jPanelFiltro.setLayout(jPanelFiltroLayout);
        jPanelFiltroLayout.setHorizontalGroup(
            jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltroLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabeldobleclick, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFiltroLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelCategoria)
                        .addGap(5, 5, 5)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        jPanelFiltroLayout.setVerticalGroup(
            jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltroLayout.createSequentialGroup()
                .addGroup(jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltroLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(jPanelFiltroLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelCategoria))
                    .addGroup(jPanelFiltroLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabeldobleclick)
                .addContainerGap())
        );

        jPanelCabecera.add(jPanelFiltro, java.awt.BorderLayout.WEST);

        jLabelEstado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(255, 51, 51));
        jLabelEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstado.setText("NO CONECTADO");
        jPanelCabecera.add(jLabelEstado, java.awt.BorderLayout.CENTER);

        jPanelBotonera.setPreferredSize(new java.awt.Dimension(265, 40));
        jPanelBotonera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 18));

        jButtonConectar.setBackground(new java.awt.Color(238, 245, 247));
        jButtonConectar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonConectar.setForeground(new java.awt.Color(255, 250, 240));
        jButtonConectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/broken-link.png"))); // NOI18N
        jButtonConectar.setActionCommand("VistaPrincipal");
        jButtonConectar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonConectar.setIconTextGap(20);
        jButtonConectar.setMaximumSize(new java.awt.Dimension(60, 40));
        jButtonConectar.setMinimumSize(new java.awt.Dimension(40, 40));
        jButtonConectar.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanelBotonera.add(jButtonConectar);

        jButtonEliminar.setBackground(new java.awt.Color(238, 245, 247));
        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 250, 240));
        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/trash-icon.png"))); // NOI18N
        jButtonEliminar.setActionCommand("VistaPrincipal");
        jButtonEliminar.setEnabled(false);
        jButtonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonEliminar.setIconTextGap(20);
        jButtonEliminar.setMaximumSize(new java.awt.Dimension(60, 40));
        jButtonEliminar.setMinimumSize(new java.awt.Dimension(40, 40));
        jButtonEliminar.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanelBotonera.add(jButtonEliminar);

        jButtonAgregar.setBackground(new java.awt.Color(238, 245, 247));
        jButtonAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(255, 250, 240));
        jButtonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/add-user-icon.png"))); // NOI18N
        jButtonAgregar.setActionCommand("VistaPrincipal");
        jButtonAgregar.setEnabled(false);
        jButtonAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonAgregar.setIconTextGap(20);
        jButtonAgregar.setMaximumSize(new java.awt.Dimension(60, 40));
        jButtonAgregar.setMinimumSize(new java.awt.Dimension(40, 40));
        jButtonAgregar.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanelBotonera.add(jButtonAgregar);

        jPanelCabecera.add(jPanelBotonera, java.awt.BorderLayout.EAST);

        jTableContactos.setBackground(new java.awt.Color(238, 245, 247));
        jTableContactos.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jTableContactos.setModel(new javax.swing.table.DefaultTableModel(

            new Object[][]{
                {null,null,null,null}
            },
            new String[]{"Id","Nombre","Apellido","Mail"}){
            public boolean isCellEditable(int row,int column){
                return false;
            }

        });
        jTableContactos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableContactos.setDragEnabled(true);
        jTableContactos.setGridColor(new java.awt.Color(36, 123, 160));
        jTableContactos.setIntercellSpacing(new java.awt.Dimension(0, 3));
        jTableContactos.setRowHeight(30);
        jTableContactos.setSelectionBackground(new java.awt.Color(75, 147, 177));
        jTableContactos.setSelectionForeground(new java.awt.Color(238, 245, 247));
        jTableContactos.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTableContactos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jPanelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 18, Short.MAX_VALUE)
                    .addComponent(jPanelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 343, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public JLabel getjLabelEstado() {
        return jLabelEstado;
    }

    public void setjLabelEstado(String estado) {
        this.jLabelEstado.setText(estado);
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public JButton getjButtonAgregar() {
        return jButtonAgregar;
    }

    public JButton getjButtonConectar() {
        return jButtonConectar;
    }

    public JButton getjButtonEliminar() {
        return jButtonEliminar;
    }

    public JTable getjTableContactos() {
        return jTableContactos;
    }
    
    public void setRow(Object[] rowData) {
        DefaultTableModel dtm = (DefaultTableModel) this.jTableContactos.getModel();
        dtm.addRow(rowData);
    }

    public JLabel getjLabeldobleclick() {
        return jLabeldobleclick;
    }

    public void limpiarTabla() {
        DefaultTableModel dtm = (DefaultTableModel) this.jTableContactos.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
    }
   
    public void configuracionJTable() {
        jTableContactos.setPreferredScrollableViewportSize(new Dimension(500, 70));
        JScrollPane scrollPane = new JScrollPane(jTableContactos);
        getContentPane().add(scrollPane, BorderLayout.CENTER);
    }
   public int  devolverId(){
    DefaultTableModel dtm = (DefaultTableModel) this.jTableContactos.getModel();
      String dato=String.valueOf(dtm.getValueAt(jTableContactos.getSelectedRow(), 0));
      
      return Integer.valueOf(dato);

}
   public void llenarTabla(LinkedList infoJtable) {
           
                    Object[] data = new Object[4];

                    int filaFin = 0;
                    for (int i = 0; i < infoJtable.size(); i++) {
                        data[filaFin] = infoJtable.get(i);
                        filaFin++;
                        if (filaFin == 4) {
                            setRow(data);
                            filaFin = 0;
                            data = new Object[4];
                        }
                    }
    }
   
    public void mensajeAdvertencia(String mensaje){
    JOptionPane.showMessageDialog(null, mensaje);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabeldobleclick;
    private javax.swing.JPanel jPanelBotonera;
    private javax.swing.JPanel jPanelCabecera;
    private javax.swing.JPanel jPanelFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableContactos;
    // End of variables declaration//GEN-END:variables
}
