/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Modelo;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Juan Pablo Palomares Avila y Alvaro Bulnes Ramos
 */
public class VistaLog extends javax.swing.JFrame {
    private VistaPrincipal principal;
    /**
     * Creates new form VistaLog
     */
    public VistaLog(){
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    public VistaLog(VistaPrincipal vistaPrincipal) {
        initComponents();
        this.principal=vistaPrincipal;
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
        
    }

    public JButton getjButtonCerrar() {
        return jButtonCerrar;
    }

    public JButton getjButtonConectar() {
        return jButtonConectar;
    }

    public String getjTextFieldUser() {
        return jTextFieldUser.getText();
    }

    public String getjTextFieldPass() {
        return jTextFieldPass.getText();
    }
    public JLabel getjLabelError() {
        return jLabelError;
    }
     public void setjLabelError(String texto) {
       jLabelError.setText(texto);
       jLabelError.setForeground(Color.red);
    }

    public JTextField getjTextFieldUrl() {
        return jTextFieldUrl;
    }

    public JTextField getjTextFieldDriver() {
        return jTextFieldDriver;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBotonera = new javax.swing.JPanel();
        jButtonConectar = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jPanelEdicion = new javax.swing.JPanel();
        jPanelLabels = new javax.swing.JPanel();
        jLabelDriver = new javax.swing.JLabel();
        jLabelUrl = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jPanelCampos = new javax.swing.JPanel();
        jTextFieldDriver = new javax.swing.JTextField();
        jTextFieldUrl = new javax.swing.JTextField();
        jTextFieldUser = new javax.swing.JTextField();
        jTextFieldPass = new javax.swing.JTextField();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanelBotonera.setPreferredSize(new java.awt.Dimension(850, 53));
        jPanelBotonera.setLayout(new javax.swing.BoxLayout(jPanelBotonera, javax.swing.BoxLayout.LINE_AXIS));

        jButtonConectar.setBackground(new java.awt.Color(238, 245, 247));
        jButtonConectar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonConectar.setForeground(new java.awt.Color(24, 19, 9));
        jButtonConectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/broken-link.png"))); // NOI18N
        jButtonConectar.setText("Conectar");
        jButtonConectar.setActionCommand("VistaLog");
        jButtonConectar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonConectar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonConectar.setIconTextGap(20);
        jButtonConectar.setPreferredSize(new java.awt.Dimension(400, 53));
        jPanelBotonera.add(jButtonConectar);

        jButtonCerrar.setBackground(new java.awt.Color(238, 245, 247));
        jButtonCerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCerrar.setForeground(new java.awt.Color(24, 19, 9));
        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/close-icon.png"))); // NOI18N
        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.setActionCommand("VistaLog");
        jButtonCerrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonCerrar.setIconTextGap(20);
        jButtonCerrar.setPreferredSize(new java.awt.Dimension(400, 53));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanelBotonera.add(jButtonCerrar);

        jPanelEdicion.setPreferredSize(new java.awt.Dimension(100, 800));
        jPanelEdicion.setLayout(new java.awt.BorderLayout(10, 0));

        jPanelLabels.setMinimumSize(new java.awt.Dimension(80, 90));
        jPanelLabels.setPreferredSize(new java.awt.Dimension(120, 800));
        jPanelLabels.setLayout(new java.awt.GridLayout(4, 1));

        jLabelDriver.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jLabelDriver.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDriver.setText("Driver:");
        jLabelDriver.setIconTextGap(15);
        jLabelDriver.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanelLabels.add(jLabelDriver);

        jLabelUrl.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jLabelUrl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUrl.setText("URL:");
        jLabelUrl.setIconTextGap(15);
        jLabelUrl.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanelLabels.add(jLabelUrl);

        jLabelUser.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUser.setText("User:");
        jLabelUser.setIconTextGap(15);
        jLabelUser.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanelLabels.add(jLabelUser);

        jLabelPass.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jLabelPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPass.setText("Pass:");
        jLabelPass.setIconTextGap(15);
        jLabelPass.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanelLabels.add(jLabelPass);

        jPanelEdicion.add(jPanelLabels, java.awt.BorderLayout.WEST);

        jPanelCampos.setMinimumSize(new java.awt.Dimension(320, 148));
        jPanelCampos.setPreferredSize(new java.awt.Dimension(320, 111));
        jPanelCampos.setLayout(new java.awt.GridLayout(4, 1));

        jTextFieldDriver.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jTextFieldDriver.setForeground(new java.awt.Color(24, 19, 9));
        jTextFieldDriver.setText("com.mysql.jdbc.Driver");
        jTextFieldDriver.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextFieldDriver.setSelectionColor(new java.awt.Color(255, 206, 91));
        jTextFieldDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDriverActionPerformed(evt);
            }
        });
        jPanelCampos.add(jTextFieldDriver);

        jTextFieldUrl.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jTextFieldUrl.setForeground(new java.awt.Color(24, 19, 9));
        jTextFieldUrl.setText("jdbc:mysql://localhost:3306/agenda");
        jTextFieldUrl.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextFieldUrl.setSelectionColor(new java.awt.Color(255, 206, 91));
        jTextFieldUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUrlActionPerformed(evt);
            }
        });
        jPanelCampos.add(jTextFieldUrl);

        jTextFieldUser.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jTextFieldUser.setForeground(new java.awt.Color(24, 19, 9));
        jTextFieldUser.setText("root");
        jTextFieldUser.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextFieldUser.setSelectionColor(new java.awt.Color(255, 206, 91));
        jPanelCampos.add(jTextFieldUser);

        jTextFieldPass.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        jTextFieldPass.setForeground(new java.awt.Color(24, 19, 9));
        jTextFieldPass.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextFieldPass.setSelectionColor(new java.awt.Color(255, 206, 91));
        jPanelCampos.add(jTextFieldPass);

        jPanelEdicion.add(jPanelCampos, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addComponent(jPanelBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jTextFieldDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDriverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDriverActionPerformed

    private void jTextFieldUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUrlActionPerformed
 
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JLabel jLabelDriver;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanelBotonera;
    private javax.swing.JPanel jPanelCampos;
    private javax.swing.JPanel jPanelEdicion;
    private javax.swing.JPanel jPanelLabels;
    private javax.swing.JTextField jTextFieldDriver;
    private javax.swing.JTextField jTextFieldPass;
    private javax.swing.JTextField jTextFieldUrl;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
